name: Build Android APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer_cmd: buildozer android debug
          
